<?php


namespace app\modules\admin\controllers;
use yii\web\Controller;
use app\modules\admin\Admin;
class IndexController extends Controller{

    public $layout='main';

    public function beforeAction($action)
    {
        if(\Yii::$app->admin->isGuest){
            $this->redirect(['login/login']);
            \Yii::$app->end();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render('index');
    }

    //    public function actionIndex1(){
    //        return '111';
    //    }
    //
    //    public function actionIndex2(){
    //        return '2222';
    //    }
}