<?php

return [

    [
        'label'=>'管理员管理',
        'icon'=>'fa-user',
        'controller'=>'manager',
        'children'=>[
            ['label'=>'管理员列表','url'=>'manager/list'],
            ['label'=>'添加管理员','url'=>'manager/add'],
        ]
    ],
    [
        'label'=>'权限管理',
        'icon'=>'fa-th-large',
        'controller'=>'rbac',
        'children'=>[
            ['label'=>'角色列表','url'=>'rbac/role-list'],
            ['label'=>'权限列表','url'=>'rbac/rule-list'],
        ]
    ],
    [
        'label'=>'用户管理',
        'icon'=>'fa-users',
        'controller'=>'user',
        'children'=>[
            ['label'=>'用户列表','url'=>'user/list']
        ]
    ],
    [
        'label'=>'分类管理',
        'icon'=>'fa-tags',
        'controller'=>'category',
        'children'=>[
            ['label'=>'分类列表','url'=>'category/list'],
            ['label'=>'添加分类','url'=>'category/add'],
        ]
    ],
    [
        'label'=>'商品管理',
        'icon'=>'fa-shopping-cart',
        'controller'=>'goods',
        'children'=>[
            ['label'=>'商品列表','url'=>'goods/list'],
            ['label'=>'添加商品','url'=>'goods/add'],
        ]
    ],
    [
        'label'=>'订单管理',
        'icon'=>'fa-list-alt',
        'controller'=>'order',
        'children'=>[
            ['label'=>'订单列表','url'=>'order/list'],
        ]
    ],
    [
        'label'=>'文章管理',
        'icon'=>'fa-book',
        'controller'=>'article',
        'children'=>[
            ['label'=>'文章列表','url'=>'article/list'],
            ['label'=>'添加文章','url'=>'article/add'],
        ]
    ],
    [
        'label'=>'链接管理',
        'icon'=>'fa-chain',
        'controller'=>'link',
        'children'=>[
            ['label'=>'链接列表','url'=>'link/list'],
            ['label'=>'添加链接','url'=>'link/add'],
        ]
    ],

];